version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./app:/app/app
      - ./wsgi.py:/app/wsgi.py
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./whisper_models:/root/.cache/whisper
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_DEBUG=1
      - SECRET_KEY=change-this-in-production
      - HOST=0.0.0.0
      - PORT=5001
      - PYTHONUNBUFFERED=1
    command: gunicorn --worker-class gthread --threads 100 -w 1 -b 0.0.0.0:5001 --log-level debug --capture-output --enable-stdio-inheritance wsgi:app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 12G
        reservations:
          cpus: '2'
          memory: 4G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 